version: '3.3'


services:
    mysql:
        image: mysql:5.7
        volumes:
         - database:/var/lib/mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: codeigniter
            MYSQL_USER: php
            MYSQL_PASSWORD: php
        networks:
          - mynet


    myphp:
        container_name: myphp
        expose:
          - "9000"
        volumes:
          - $HOME/codeigniter/src/docker/myphp:/var/www/html
        depends_on:
          - mysql
        build: 
            context: './src/docker/myphp'
            dockerfile: dockerfile 
        networks:
          - mynet

    mynginx:
        image: nginx:latest
        container_name: mynginx
        ports: 
          - "8080:80"
        depends_on:
          - myphp
        volumes:
          - $HOME/codeigniter/src/docker/mynginx/nginx.ini:/etc/nginx/conf.d/default.conf
          - $HOME/codeigniter/src/docker/mynginx:/var/www/html
        networks:
          - mynet
        
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpMyAdmin
        ports:
          - "8082:80"
        environment:
            PMA_HOST: mysql
        networks:
          - mynet

volumes:
    database: {}

networks:
    mynet:
        driver: bridge